FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
RUN apt-get update -y && apt-get install python -y && curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /bin/youtube-dl && chmod a+rx /bin/youtube-dl
WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "youtube-subs.dll"]
