FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
RUN apt-get update -y && apt-get install python -y
WORKDIR /app
COPY . .
COPY extractors.py youtube-dl/youtube_dl/extractor/extractors.py
ENTRYPOINT ["dotnet", "youtube-subs.dll"]
